# Generated by Django 3.0.2 on 2020-04-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_validation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='added_on',
        ),
        migrations.AddField(
            model_name='monitor',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=50),
        ),
    ]
