# Generated by Django 3.0.2 on 2020-04-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_validation', '0002_auto_20200425_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='email',
            field=models.EmailField(blank=True, default='User.EMAIL_FIELD', max_length=50),
        ),
    ]
