# Generated by Django 3.0.2 on 2020-04-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_validation', '0003_auto_20200425_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='email',
            field=models.EmailField(blank=True, default='email', max_length=50),
        ),
    ]
